//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Resources;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: AssemblyDescription("ILogInject.Unity enables the Unity IOC container to inject a CommonLogging.ILog c" +
    "lass logger into a registered class.")]
[assembly: AssemblyCompany("github.com/trondr")]
[assembly: AssemblyProduct("ILogInject.Unity")]
[assembly: AssemblyCopyright("Copyright © <github.com/trondr> 2013")]
[assembly: CLSCompliant(true)]
[assembly: AssemblyInformationalVersion("1.0.13134.2f0d121")]
[assembly: AssemblyVersion("1.0.13134.10")]
[assembly: AssemblyFileVersion("1.0.13134.10")]


